In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns
%matplotlib inline

In [3]:

df1 = pd.read_csv("C:\\Users\\RASHMI\\Desktop\\SIH\\1.csv")

In [4]:
df1.head()

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,skills,min_qualifications
0,Google,Google Cloud Program Manager,Program Management,Singapore,"Shape, shepherd, ship, and show technical prog...",BA/BS degree or equivalent practical experienc...,Experience in the business technology market a...,"management,communication,coding,marketing,lead...",BA/BS
1,Google,"Supplier Development Engineer (SDE), Cable/Con...",Manufacturing & Supply Chain,"Shanghai, China",Drive cross-functional activities in the suppl...,BS degree in an Engineering discipline or equi...,"BSEE, BSME or BSIE degree.\nExperience of usin...","management,communication,marketing,leadership,...",engineering
2,Google,"Data Analyst, Product and Tools Operations, Go...",Technical Solutions,"New York, NY, United States",Collect and analyze data to draw insight and i...,"Bachelor’s degree in Business, Economics, Stat...",Experience partnering or consulting cross-func...,"DA,coding,accounting,math,communication",BBA
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and...",BA/BS degree in Computer Science or equivalent...,"Experience as a software developer, architect,...","webDev,coding,communication,leadership,DA",BA/BS
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nPr...,BA/BS degree or equivalent practical experienc...,CTS Certification.\nExperience in the construc...,"leadership,communication,marketing,management",BA/BS

In [5]:

pd.get_dummies(df1[["Category"]]).head()

,Category_Business Strategy,Category_Data Center & Network,Category_Developer Relations,Category_Hardware Engineering,Category_Manufacturing & Supply Chain,Category_Partnerships,Category_Product & Customer Support,Category_Program Management,Category_Software Engineering,Category_Technical Solutions,Category_Technical Writing
0,0,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,1,0
3,0,0,1,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,0

In [6]:
df1_skills = df1["skills"].str.get_dummies(sep=",")
                            

df1_skills.head()

,DA,accounting,advertising,coding,communication,designing,languages,leadership,management,marketing,math,webDev
0,0,0,0,1,1,0,0,1,1,1,0,0
1,0,1,0,0,1,0,0,1,1,1,0,0
2,1,1,0,1,1,0,0,0,0,0,1,0
3,1,0,0,1,1,0,0,1,0,0,0,1
4,0,0,0,0,1,0,0,1,1,1,0,0

In [7]:
df1.isnull().sum()

Company                     0
Title                       0
Category                    0
Location                    0
Responsibilities            1
Minimum Qualifications      1
Preferred Qualifications    1
skills                      0
min_qualifications          1
dtype: int64

In [8]:
df1.dropna(subset=['Minimum Qualifications'])

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,skills,min_qualifications
0,Google,Google Cloud Program Manager,Program Management,Singapore,"Shape, shepherd, ship, and show technical prog...",BA/BS degree or equivalent practical experienc...,Experience in the business technology market a...,"management,communication,coding,marketing,lead...",BA/BS
1,Google,"Supplier Development Engineer (SDE), Cable/Con...",Manufacturing & Supply Chain,"Shanghai, China",Drive cross-functional activities in the suppl...,BS degree in an Engineering discipline or equi...,"BSEE, BSME or BSIE degree.\nExperience of usin...","management,communication,marketing,leadership,...",engineering
2,Google,"Data Analyst, Product and Tools Operations, Go...",Technical Solutions,"New York, NY, United States",Collect and analyze data to draw insight and i...,"Bachelor’s degree in Business, Economics, Stat...",Experience partnering or consulting cross-func...,"DA,coding,accounting,math,communication",BBA
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and...",BA/BS degree in Computer Science or equivalent...,"Experience as a software developer, architect,...","webDev,coding,communication,leadership,DA",BA/BS
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nPr...,BA/BS degree or equivalent practical experienc...,CTS Certification.\nExperience in the construc...,"leadership,communication,marketing,management",BA/BS
5,Google,"Associate Account Strategist (Czech/Slovak), G...",Technical Solutions,"Dublin, Ireland",Communicate with customers via phone and email...,Bachelor's degree or equivalent practical expe...,"Experience in sales, customer service, account...","communication,languages,accounting",engineering
6,Google,"Supplier Development Engineer, Camera, Consume...",Hardware Engineering,"Mountain View, CA, United States",Manage cross-functional activities in the supp...,BS degree in Engineering or equivalent practic...,Master's degree.\nExperience in the developmen...,"communication,management,leadership,DA,coding",BS
7,Google,"Strategic Technology Partner Manager, Healthca...",Partnerships,"Sunnyvale, CA, United States",Lead the development and strategy with partner...,BA/BS degree or equivalent practical experienc...,"BA/BS degree in a technical, life sciences or ...","communication,leadership,marketing,management,...",BA/BS
8,Google,"Manufacturing Business Manager, Google Hardware",Manufacturing & Supply Chain,"Xinyi District, Taiwan",Develop CM/ODM strategy and implement supplier...,"BA/BS degree in Engineering, Supply Chain or e...",MBA degree.\nExperience in procurement and sup...,"communication,marketing,management,math,accoun...",engineering
9,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"New York, NY, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","coding,DA,",BA/BS
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",Build and maintain the Support Operations Anal...,"BA/BS degree in Computer Science, Engineering,...",Experience in designing and executing structur...,"webDev,coding,communication,leadership,DA",BA/BS
11,Google,Partner Onboarding Manager (Americas),Partnerships,"Seattle, WA, United States",Serve as point of contact for Partners and man...,Bachelor's degree or equivalent practical expe...,Master's degree in technical field (Computer S...,"management,accounting,webDev,languages,communi...",engineering
12,Google,"Associate Account Strategist (Ukrainian), GMS ...",Technical Solutions,"Dublin, Ireland",Implement creative ways to improve our custome...,Bachelor's degree or equivalent practical expe...,"Experience in leading, motivating and working ...","designing,languages,management,marketing",BBA
13,Google,"Survey Lead, Google Cloud Support",Product & Customer Support,"New York, NY, United States",Develop and track core metrics across all Goog...,BA/BS degree in a technical or quantitative/bu...,"MBA, MS or PhD degree in a related or quantita...","coding,accounting,DA,math,",BBA
14,Google,"Solution Architect, Google Cloud Platform (Api...",Technical Solutions,"Amsterdam, Netherlands","Produce required design specifications, provid...",BA/BS degree in a technical or engineering fie...,Experience with or deep understanding of priva...,"designing,coding,accounting,math,communication",engineering
16,Google,"Machine Learning Product Specialist, Google Cl...",Technical Solutions,"Frankfurt, Germany",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or a relat...,"marketing,advertising,webDev,leadership,manage...",engineering
17,Google,"Software Engineering Manager, Cloud Storage, S...",Software Engineering,"Dublin, Ireland",Lead a team of software and systems engineers ...,BA/BS degree in Computer Science or related te...,Hands-on technical experience.\nCapable of tec...,"leadership,communication,marketing,management,...",BA/BS
18,Google,"Global Supply Chain Manager, Display/Touch, Co...",Hardware Engineering,"Xinyi District, Taiwan",Develop and implement global supply chain stra...,"BA/BS in Electrical Engineering, Mechanical En...",5 years of relevant work experience in global ...,"accounting,marketing,advertising,math",BA/BS
19,Google,"Technical Program Manager, ASIC Development",Program Management,"Sunnyvale, CA, United States","Plan, coordinate, and deliver platforms hardwa...","BS degree in Electrical Engineering, Computer ...",Master's or PhD degree in engineering.\nExperi...,"management,communication,math,coding,DA",BS
20,Google,"Quantitative Analyst, Ads Quality",Product & Customer Support,"Zürich, Switzerland",Apply advanced statistical methods and work wi...,PhD in Statistics or Econometrics or a related...,Relevant industry or research experience.\nFam...,"math,coding,DA,communication,management",PhD
21,Google,"Software Engineer Manager, Tools and Infrastru...",Software Engineering,"London, United Kingdom",Build and manage an engineering productivity t...,BA/BS degree in Computer Science or other rela...,"Master's degree or PhD in Computer Science, Ar...","management,communication,leadership,math,coding",BA/BS
22,Google,Head of Professional Services,Program Management,"London, United Kingdom",Set the standard for successful delivery and e...,BA/BS degree or equivalent practical experienc...,Experience in application/workload migration w...,"designing,management,coding,math,marketing",BA/BS
23,Google,"Survey Lead, Google Cloud Support",Product & Customer Support,"Sunnyvale, CA, United States",Develop and track core metrics across all Goog...,BA/BS degree in a technical or quantitative/bu...,"MBA, MS or PhD degree in a related or quantita...","coding,math,DA,management,accounting,communica...",BA/BS
24,Google,"Technical Trainer Manager, Google Cloud",Program Management,"Sunnyvale, CA, United States",Manage a global team of Technical Trainers.\nG...,7 years of experience in a Technical Training ...,"Experience with Cloud Infrastructure, Data and...","management,coding,math,DA,communication,leader...",experience
25,Google,"Partner Sales Engineer, Google Cloud",Technical Solutions,"München, Germany",Work with Partner Managers to identify and rec...,Bachelor's degree in Computer Science or a rel...,"Experience in, and understanding of, data and ...","communication,leadership,management,math,langu...",engineering
26,Google,"Technical Solutions Engineer, Chrome and Andro...",Technical Solutions,"Zürich, Switzerland",Obtain and maintain an in-depth understanding ...,"Bachelor's degree in Computer Science, or a re...","Hands-on experience implementing, troubleshoot...","coding,DA,accounting,math,designing",engineering
27,Google,"Program Manager, Supply Chain Data Management",Data Center & Network,"Sunnyvale, CA, United States",Understand the supply chain data structure and...,5 years of experience in supply chain operatio...,Ability to work independently with minimal gui...,"DA,coding,accounting,math,communication",experience
28,Google,"Machine Learning Product Specialist, Google Cl...",Technical Solutions,"Berlin, Germany",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or a relat...,"management,leadership,accounting,communication",BA/BS
29,Google,"Head of Partner Engineering, Google Cloud",Technical Solutions,Singapore,Work with JAPAC Partner and Alliances Lead to ...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or other r...,"leadership,communication,marketing,management",BA/BS
30,Google,"Presales Manager, New Business Development",Program Management,"New York, NY, United States","Oversee a sales program across office(s), resp...",BA/BS degree or equivalent practical experienc...,Experience in Sales Management and/or Sales Op...,"management,marketing,designing,communication",BA/BS
31,Google,"Technical Solutions Consultant, Google Technic...",Technical Solutions,"Hamburg, Germany","Work closely with our Sales team to identify, ...",BA/BS degree in Computer Science or a related ...,Experience working with and managing external ...,"marketing,advertising,webDev,leadership,manage...",engineering
32,Google,"Solutions Consultant, Ads, Google Professional...",Product & Customer Support,"San Francisco, CA, United States","Provide consulting services, share best practi...",BA/BS degree in Computer Science or equivalent...,Experience managing technical system implement...,"coding,accounting,DA,math,",engineering
33,Google,"Chief of Staff, Google Hardware",Business Strategy,"Mountain View, CA, United States",Develop a key performance indicators (KPI) das...,BA/BS degree or equivalent practical experienc...,MBA and/or graduate degree.\nExperience partne...,"coding,math,DA,management,accounting,communica...",BA/BS
34,Google,"Measurement Solutions Consultant, Google Techn...",Technical Solutions,"Dublin, Ireland",Guide partners and clients through the entire ...,Experience managing analytics solutions.\nExpe...,Experience using and/or deploying digital anal...,"communication,coding,accounting,math",experience
35,Google,"Big Data Product Specialist, Google Cloud (Eng...",Technical Solutions,"Milan, Italy",Work as part of the Sales team to identify and...,"BA/BS degree in Computer Science, or a related...",Master's degree in Computer Science or a relat...,"marketing,advertising,webDev,leadership,manage...",engineering
36,Google,"Global Supply Chain Manager, Cable and Connect...",Manufacturing & Supply Chain,"Shanghai, China",Develop and execute global supply chain strate...,"Bachelor's degree in Electrical Engineering, M...",5 years of relevant work experience in global ...,"marketing,advertising,webDev,leadership,manage...",engineering
37,Google,Technical Contracts Manager,Technical Solutions,"Mountain View, CA, United States",Coordinate and facilitate between internal tea...,"BA/BS degree in Business, Computer Science or ...","MBA, MS, JD or other advanced degree.\n2 years...","communication,leadership,management,math,langu...",BBA
38,Google,"High Performance Computing (HPC) Specialist, G...",Program Management,"London, United Kingdom",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or related te...,Master's degree in Computer Science or other t...,"management,communication,leadership,math,coding",engineering
39,Google,"Technical Program Manager, Google Cloud Functions",Program Management,"Warszawa, Poland",Align Googlers from multiple organization to d...,BS degree in a technical discipline (e.g. Comp...,Master's degree in a technical discipline (e.g...,"management,communication,leadership,math,coding",engineering
40,Google,Software Engineer,Software Engineering,"Irvine, CA, United States","Design, develop, test, deploy, maintain and im...",BA/BS degree in Computer Science or similar te...,"Master’s, PhD degree, further education or exp...","designing,management,coding,math,marketing",engineering
41,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"Sunnyvale, CA, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","coding,math,DA,management,accounting,communica...",BA/BS
42,Google,"Program Manager, Operations, Google Cloud Web",Program Management,"Sunnyvale, CA, United States",Provide Program Management support to Google C...,4 years of experience in Program Management wo...,"Demonstrated Project Management skills, with t...","coding,accounting,DA,math,",experience
43,Google,"High Performance Computing (HPC) Specialist, G...",Program Management,"Paris, France",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or related te...,Master's degree in Computer Science or other t...,"marketing,advertising,webDev,leadership,manage...",engineering
44,Google,"Vendor Operations Specialist (EMEA), Google Te...",Technical Solutions,"Dublin, Ireland",Support the management of outsourced operation...,Bachelor's degree or equivalent practical expe...,Project management experience.\nResource Plann...,"management,communication,DA,leadership,account...",engineering
45,Google,"Solution Architect, Google Cloud Platform (Api...",Technical Solutions,"Berlin, Germany","Produce required design specifications, provid...",BA/BS degree in a technical or engineering fie...,Experience with or deep understanding of priva...,"designing,accounting,math,webDev",engineering
46,Google,"Graphics Software Engineer, Robotics Simulatio...",Software Engineering,"München, Germany",Manage feature development for graphics modeli...,"BA/BS in Computer Science or Robotics, or equi...",Experience writing highly optimized and effici...,"designing,management,coding,math,marketing",engineering
47,Google,"Technical Writer, University Graduate",Technical Writing,"Kirkland, WA, United States",Write technical documentation for our external...,BA/BS degree or equivalent practical experienc...,Graduating from BA/BS degree or MA/MS degree i...,"coding,math,DA,management,accounting,communica...",BA/BS
48,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"Cambridge, MA, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","communication,languages,accounting",BA/BS

In [9]:
df1.isnull().sum()

Company                     0
Title                       0
Category                    0
Location                    0
Responsibilities            1
Minimum Qualifications      1
Preferred Qualifications    1
skills                      0
min_qualifications          1
dtype: int64

In [10]:

from sklearn.neighbors import NearestNeighbors

In [11]:
df2=pd.concat([df1["skills"].str.get_dummies(sep=","),pd.get_dummies(df1[["min_qualifications"]])],axis=1)

In [12]:
df=pd.concat([df1,df2])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.

In [13]:
df1

,Company,Title,Category,Location,Responsibilities,Minimum Qualifications,Preferred Qualifications,skills,min_qualifications
0,Google,Google Cloud Program Manager,Program Management,Singapore,"Shape, shepherd, ship, and show technical prog...",BA/BS degree or equivalent practical experienc...,Experience in the business technology market a...,"management,communication,coding,marketing,lead...",BA/BS
1,Google,"Supplier Development Engineer (SDE), Cable/Con...",Manufacturing & Supply Chain,"Shanghai, China",Drive cross-functional activities in the suppl...,BS degree in an Engineering discipline or equi...,"BSEE, BSME or BSIE degree.\nExperience of usin...","management,communication,marketing,leadership,...",engineering
2,Google,"Data Analyst, Product and Tools Operations, Go...",Technical Solutions,"New York, NY, United States",Collect and analyze data to draw insight and i...,"Bachelor’s degree in Business, Economics, Stat...",Experience partnering or consulting cross-func...,"DA,coding,accounting,math,communication",BBA
3,Google,"Developer Advocate, Partner Engineering",Developer Relations,"Mountain View, CA, United States","Work one-on-one with the top Android, iOS, and...",BA/BS degree in Computer Science or equivalent...,"Experience as a software developer, architect,...","webDev,coding,communication,leadership,DA",BA/BS
4,Google,"Program Manager, Audio Visual (AV) Deployments",Program Management,"Sunnyvale, CA, United States",Plan requirements with internal customers.\nPr...,BA/BS degree or equivalent practical experienc...,CTS Certification.\nExperience in the construc...,"leadership,communication,marketing,management",BA/BS
5,Google,"Associate Account Strategist (Czech/Slovak), G...",Technical Solutions,"Dublin, Ireland",Communicate with customers via phone and email...,Bachelor's degree or equivalent practical expe...,"Experience in sales, customer service, account...","communication,languages,accounting",engineering
6,Google,"Supplier Development Engineer, Camera, Consume...",Hardware Engineering,"Mountain View, CA, United States",Manage cross-functional activities in the supp...,BS degree in Engineering or equivalent practic...,Master's degree.\nExperience in the developmen...,"communication,management,leadership,DA,coding",BS
7,Google,"Strategic Technology Partner Manager, Healthca...",Partnerships,"Sunnyvale, CA, United States",Lead the development and strategy with partner...,BA/BS degree or equivalent practical experienc...,"BA/BS degree in a technical, life sciences or ...","communication,leadership,marketing,management,...",BA/BS
8,Google,"Manufacturing Business Manager, Google Hardware",Manufacturing & Supply Chain,"Xinyi District, Taiwan",Develop CM/ODM strategy and implement supplier...,"BA/BS degree in Engineering, Supply Chain or e...",MBA degree.\nExperience in procurement and sup...,"communication,marketing,management,math,accoun...",engineering
9,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"New York, NY, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","coding,DA,",BA/BS
10,Google,"Data Analyst, Consumer Hardware",Product & Customer Support,"Mountain View, CA, United States",Build and maintain the Support Operations Anal...,"BA/BS degree in Computer Science, Engineering,...",Experience in designing and executing structur...,"webDev,coding,communication,leadership,DA",BA/BS
11,Google,Partner Onboarding Manager (Americas),Partnerships,"Seattle, WA, United States",Serve as point of contact for Partners and man...,Bachelor's degree or equivalent practical expe...,Master's degree in technical field (Computer S...,"management,accounting,webDev,languages,communi...",engineering
12,Google,"Associate Account Strategist (Ukrainian), GMS ...",Technical Solutions,"Dublin, Ireland",Implement creative ways to improve our custome...,Bachelor's degree or equivalent practical expe...,"Experience in leading, motivating and working ...","designing,languages,management,marketing",BBA
13,Google,"Survey Lead, Google Cloud Support",Product & Customer Support,"New York, NY, United States",Develop and track core metrics across all Goog...,BA/BS degree in a technical or quantitative/bu...,"MBA, MS or PhD degree in a related or quantita...","coding,accounting,DA,math,",BBA
14,Google,"Solution Architect, Google Cloud Platform (Api...",Technical Solutions,"Amsterdam, Netherlands","Produce required design specifications, provid...",BA/BS degree in a technical or engineering fie...,Experience with or deep understanding of priva...,"designing,coding,accounting,math,communication",engineering
15,Google,Manufacturing Test Engineer,Hardware Engineering,"South San Francisco, CA, United States",NaN,NaN,NaN,"leadership,communication,marketing,management",NaN
16,Google,"Machine Learning Product Specialist, Google Cl...",Technical Solutions,"Frankfurt, Germany",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or a relat...,"marketing,advertising,webDev,leadership,manage...",engineering
17,Google,"Software Engineering Manager, Cloud Storage, S...",Software Engineering,"Dublin, Ireland",Lead a team of software and systems engineers ...,BA/BS degree in Computer Science or related te...,Hands-on technical experience.\nCapable of tec...,"leadership,communication,marketing,management,...",BA/BS
18,Google,"Global Supply Chain Manager, Display/Touch, Co...",Hardware Engineering,"Xinyi District, Taiwan",Develop and implement global supply chain stra...,"BA/BS in Electrical Engineering, Mechanical En...",5 years of relevant work experience in global ...,"accounting,marketing,advertising,math",BA/BS
19,Google,"Technical Program Manager, ASIC Development",Program Management,"Sunnyvale, CA, United States","Plan, coordinate, and deliver platforms hardwa...","BS degree in Electrical Engineering, Computer ...",Master's or PhD degree in engineering.\nExperi...,"management,communication,math,coding,DA",BS
20,Google,"Quantitative Analyst, Ads Quality",Product & Customer Support,"Zürich, Switzerland",Apply advanced statistical methods and work wi...,PhD in Statistics or Econometrics or a related...,Relevant industry or research experience.\nFam...,"math,coding,DA,communication,management",PhD
21,Google,"Software Engineer Manager, Tools and Infrastru...",Software Engineering,"London, United Kingdom",Build and manage an engineering productivity t...,BA/BS degree in Computer Science or other rela...,"Master's degree or PhD in Computer Science, Ar...","management,communication,leadership,math,coding",BA/BS
22,Google,Head of Professional Services,Program Management,"London, United Kingdom",Set the standard for successful delivery and e...,BA/BS degree or equivalent practical experienc...,Experience in application/workload migration w...,"designing,management,coding,math,marketing",BA/BS
23,Google,"Survey Lead, Google Cloud Support",Product & Customer Support,"Sunnyvale, CA, United States",Develop and track core metrics across all Goog...,BA/BS degree in a technical or quantitative/bu...,"MBA, MS or PhD degree in a related or quantita...","coding,math,DA,management,accounting,communica...",BA/BS
24,Google,"Technical Trainer Manager, Google Cloud",Program Management,"Sunnyvale, CA, United States",Manage a global team of Technical Trainers.\nG...,7 years of experience in a Technical Training ...,"Experience with Cloud Infrastructure, Data and...","management,coding,math,DA,communication,leader...",experience
25,Google,"Partner Sales Engineer, Google Cloud",Technical Solutions,"München, Germany",Work with Partner Managers to identify and rec...,Bachelor's degree in Computer Science or a rel...,"Experience in, and understanding of, data and ...","communication,leadership,management,math,langu...",engineering
26,Google,"Technical Solutions Engineer, Chrome and Andro...",Technical Solutions,"Zürich, Switzerland",Obtain and maintain an in-depth understanding ...,"Bachelor's degree in Computer Science, or a re...","Hands-on experience implementing, troubleshoot...","coding,DA,accounting,math,designing",engineering
27,Google,"Program Manager, Supply Chain Data Management",Data Center & Network,"Sunnyvale, CA, United States",Understand the supply chain data structure and...,5 years of experience in supply chain operatio...,Ability to work independently with minimal gui...,"DA,coding,accounting,math,communication",experience
28,Google,"Machine Learning Product Specialist, Google Cl...",Technical Solutions,"Berlin, Germany",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or a relat...,"management,leadership,accounting,communication",BA/BS
29,Google,"Head of Partner Engineering, Google Cloud",Technical Solutions,Singapore,Work with JAPAC Partner and Alliances Lead to ...,BA/BS degree in Computer Science or a related ...,Master's degree in Computer Science or other r...,"leadership,communication,marketing,management",BA/BS
30,Google,"Presales Manager, New Business Development",Program Management,"New York, NY, United States","Oversee a sales program across office(s), resp...",BA/BS degree or equivalent practical experienc...,Experience in Sales Management and/or Sales Op...,"management,marketing,designing,communication",BA/BS
31,Google,"Technical Solutions Consultant, Google Technic...",Technical Solutions,"Hamburg, Germany","Work closely with our Sales team to identify, ...",BA/BS degree in Computer Science or a related ...,Experience working with and managing external ...,"marketing,advertising,webDev,leadership,manage...",engineering
32,Google,"Solutions Consultant, Ads, Google Professional...",Product & Customer Support,"San Francisco, CA, United States","Provide consulting services, share best practi...",BA/BS degree in Computer Science or equivalent...,Experience managing technical system implement...,"coding,accounting,DA,math,",engineering
33,Google,"Chief of Staff, Google Hardware",Business Strategy,"Mountain View, CA, United States",Develop a key performance indicators (KPI) das...,BA/BS degree or equivalent practical experienc...,MBA and/or graduate degree.\nExperience partne...,"coding,math,DA,management,accounting,communica...",BA/BS
34,Google,"Measurement Solutions Consultant, Google Techn...",Technical Solutions,"Dublin, Ireland",Guide partners and clients through the entire ...,Experience managing analytics solutions.\nExpe...,Experience using and/or deploying digital anal...,"communication,coding,accounting,math",experience
35,Google,"Big Data Product Specialist, Google Cloud (Eng...",Technical Solutions,"Milan, Italy",Work as part of the Sales team to identify and...,"BA/BS degree in Computer Science, or a related...",Master's degree in Computer Science or a relat...,"marketing,advertising,webDev,leadership,manage...",engineering
36,Google,"Global Supply Chain Manager, Cable and Connect...",Manufacturing & Supply Chain,"Shanghai, China",Develop and execute global supply chain strate...,"Bachelor's degree in Electrical Engineering, M...",5 years of relevant work experience in global ...,"marketing,advertising,webDev,leadership,manage...",engineering
37,Google,Technical Contracts Manager,Technical Solutions,"Mountain View, CA, United States",Coordinate and facilitate between internal tea...,"BA/BS degree in Business, Computer Science or ...","MBA, MS, JD or other advanced degree.\n2 years...","communication,leadership,management,math,langu...",BBA
38,Google,"High Performance Computing (HPC) Specialist, G...",Program Management,"London, United Kingdom",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or related te...,Master's degree in Computer Science or other t...,"management,communication,leadership,math,coding",engineering
39,Google,"Technical Program Manager, Google Cloud Functions",Program Management,"Warszawa, Poland",Align Googlers from multiple organization to d...,BS degree in a technical discipline (e.g. Comp...,Master's degree in a technical discipline (e.g...,"management,communication,leadership,math,coding",engineering
40,Google,Software Engineer,Software Engineering,"Irvine, CA, United States","Design, develop, test, deploy, maintain and im...",BA/BS degree in Computer Science or similar te...,"Master’s, PhD degree, further education or exp...","designing,management,coding,math,marketing",engineering
41,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"Sunnyvale, CA, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","coding,math,DA,management,accounting,communica...",BA/BS
42,Google,"Program Manager, Operations, Google Cloud Web",Program Management,"Sunnyvale, CA, United States",Provide Program Management support to Google C...,4 years of experience in Program Management wo...,"Demonstrated Project Management skills, with t...","coding,accounting,DA,math,",experience
43,Google,"High Performance Computing (HPC) Specialist, G...",Program Management,"Paris, France",Work as part of the Sales team to identify and...,BA/BS degree in Computer Science or related te...,Master's degree in Computer Science or other t...,"marketing,advertising,webDev,leadership,manage...",engineering
44,Google,"Vendor Operations Specialist (EMEA), Google Te...",Technical Solutions,"Dublin, Ireland",Support the management of outsourced operation...,Bachelor's degree or equivalent practical expe...,Project management experience.\nResource Plann...,"management,communication,DA,leadership,account...",engineering
45,Google,"Solution Architect, Google Cloud Platform (Api...",Technical Solutions,"Berlin, Germany","Produce required design specifications, provid...",BA/BS degree in a technical or engineering fie...,Experience with or deep understanding of priva...,"designing,accounting,math,webDev",engineering
46,Google,"Graphics Software Engineer, Robotics Simulatio...",Software Engineering,"München, Germany",Manage feature development for graphics modeli...,"BA/BS in Computer Science or Robotics, or equi...",Experience writing highly optimized and effici...,"designing,management,coding,math,marketing",engineering
47,Google,"Technical Writer, University Graduate",Technical Writing,"Kirkland, WA, United States",Write technical documentation for our external...,BA/BS degree or equivalent practical experienc...,Graduating from BA/BS degree or MA/MS degree i...,"coding,math,DA,management,accounting,communica...",BA/BS
48,Google,"Solutions Architect, Healthcare and Life Scien...",Technical Solutions,"Cambridge, MA, United States",Help compile customer requirements as well as ...,"BA/BS degree in Computer Science, related Soft...","Master's degree in Computer Science, related E...","communication,languages,accounting",BA/BS

In [14]:
df2.head()

,DA,accounting,advertising,coding,communication,designing,languages,leadership,management,marketing,math,webDev,min_qualifications_BA/BS,min_qualifications_BBA,min_qualifications_BS,min_qualifications_PhD,min_qualifications_engineering,min_qualifications_experience
0,0,0,0,1,1,0,0,1,1,1,0,0,1,0,0,0,0,0
1,0,1,0,0,1,0,0,1,1,1,0,0,0,0,0,0,1,0
2,1,1,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0
3,1,0,0,1,1,0,0,1,0,0,0,1,1,0,0,0,0,0
4,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0

In [15]:
from sklearn.neighbors import NearestNeighbors

In [ ]:
def print_job_titles(query=None):
    
    if query:
        for query in df1["skills"][1:]:
            print(anime.ix[id]["Title"])

In [ ]:
print_job_titles("leadership")

In [ ]:
X = df1.iloc[:, 3:].values

In [ ]:
Y=df1["Title"]

In [17]:
x_train=df1.drop(columns=['Company','Title', 'Responsibilities','Preferred Qualifications'])
X_train=df2
y_train=df1["Title"]

In [18]:
data = [{'DA': 1, 'accounting': 0,'advertising':0,'coding':1,'communication':1,'designing':0,'languages':0,'leadership':1,'management':1,'marketing':1,'math':0,'webDev':1,'min_qualifications_BA/BS':0,'min_qualifications_BBA':0,'min_qualifications_BS':0,'min_qualifications_PhD':0,'min_qualifications_engineering':1,'min_qualifications_experience':0}]
student_details=[{'id':1, 'name':'Ashwin','college_id':'19'}]
x_test=pd.DataFrame(data,index=[50])
student = pd.read_csv("C:\\Users\\RASHMI\\Desktop\\SIH\\student_final.csv")

In [19]:
student.dropna()
stu=pd.concat([student["skills"].str.get_dummies(sep=","),pd.get_dummies(df1[["min_qualifications"]])],axis=1)

In [20]:
stu.dropna()

,DA,accounting,advertising,coding,communication,designing,languages,leadership,management,marketing,math,webDev,min_qualifications_BA/BS,min_qualifications_BBA,min_qualifications_BS,min_qualifications_PhD,min_qualifications_engineering,min_qualifications_experience
0,0,0,1,0,0,0,0,1,0,1,0,1,1.0,0.0,0.0,0.0,0.0,0.0
1,0,0,0,0,1,0,0,1,0,1,0,0,0.0,0.0,0.0,0.0,1.0,0.0
2,0,1,0,0,0,0,0,0,0,1,1,0,0.0,1.0,0.0,0.0,0.0,0.0
3,0,0,0,0,1,0,0,0,1,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
4,0,0,0,0,1,0,0,0,1,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
5,0,0,0,1,1,0,0,1,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
6,0,0,0,1,0,1,0,0,1,1,1,0,0.0,0.0,1.0,0.0,0.0,0.0
7,0,1,0,0,1,0,0,0,1,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
8,1,0,0,1,1,0,0,1,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
9,0,0,0,0,0,0,1,1,1,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
10,0,1,0,0,0,1,0,0,0,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
11,1,1,0,1,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
12,0,1,0,0,1,0,0,0,1,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
13,0,0,0,0,1,0,0,0,1,1,0,0,0.0,1.0,0.0,0.0,0.0,0.0
14,1,0,0,0,0,1,0,0,1,1,0,0,0.0,0.0,0.0,0.0,1.0,0.0
15,0,0,1,0,0,0,0,1,1,1,0,0,0.0,0.0,0.0,0.0,0.0,0.0
16,1,0,0,1,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
17,0,1,0,0,1,0,0,0,1,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
18,0,1,0,0,1,0,0,0,0,0,1,0,1.0,0.0,0.0,0.0,0.0,0.0
19,0,0,1,0,0,0,0,1,1,1,0,0,0.0,0.0,1.0,0.0,0.0,0.0
20,0,0,0,1,0,0,0,1,1,1,0,1,0.0,0.0,0.0,1.0,0.0,0.0
21,0,0,0,0,0,0,0,1,1,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0
22,0,0,1,0,0,0,0,1,1,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0
23,0,0,1,0,0,0,0,1,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0
24,1,1,1,1,0,0,1,0,0,0,0,1,0.0,0.0,0.0,0.0,0.0,1.0
25,1,1,0,1,0,0,0,0,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
26,0,1,0,1,1,1,0,0,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
27,1,0,0,1,1,0,0,1,1,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
28,0,0,0,0,1,0,0,1,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
29,0,1,0,0,1,0,1,0,0,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
30,0,1,0,1,0,0,0,0,1,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0
31,0,0,0,0,0,0,0,1,1,1,0,0,0.0,0.0,0.0,0.0,1.0,0.0
32,0,1,0,1,1,1,0,0,0,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
33,0,0,0,0,1,0,0,1,1,0,0,0,1.0,0.0,0.0,0.0,0.0,0.0
34,0,0,0,0,1,0,1,0,1,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
35,0,0,1,0,0,0,0,1,1,1,0,0,0.0,0.0,0.0,0.0,1.0,0.0
36,1,0,0,1,0,0,0,0,1,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
37,0,0,0,0,1,0,1,0,1,0,0,0,0.0,1.0,0.0,0.0,0.0,0.0
38,0,1,1,0,0,0,1,0,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
39,1,0,1,1,0,0,0,1,0,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0
40,0,0,1,0,0,0,0,0,1,1,0,0,0.0,0.0,0.0,0.0,1.0,0.0
41,0,0,1,0,0,0,0,1,0,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0
42,1,0,0,1,0,0,0,0,0,0,1,1,0.0,0.0,0.0,0.0,0.0,1.0
43,0,0,0,0,1,0,0,0,1,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
44,0,0,0,0,1,0,0,1,1,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
45,0,0,0,1,0,1,0,0,1,0,1,0,0.0,0.0,0.0,0.0,1.0,0.0
46,1,0,0,1,0,0,0,1,1,0,0,1,0.0,0.0,0.0,0.0,1.0,0.0
47,0,0,0,0,1,0,0,1,1,1,0,0,1.0,0.0,0.0,0.0,0.0,0.0
48,1,0,0,1,1,0,0,1,0,0,0,1,1.0,0.0,0.0,0.0,0.0,0.0

In [21]:
X_test=stu

X_test.isnull().sum()

DA                                0
accounting                        0
advertising                       0
coding                            0
communication                     0
designing                         0
languages                         0
leadership                        0
management                        0
marketing                         0
math                              0
webDev                            0
min_qualifications_BA/BS          5
min_qualifications_BBA            5
min_qualifications_BS             5
min_qualifications_PhD            5
min_qualifications_engineering    5
min_qualifications_experience     5
dtype: int64

In [22]:
X_test=X_test.dropna()

In [23]:
cols = ['min_qualifications_BA/BS', 'min_qualifications_BBA','min_qualifications_BS','min_qualifications_PhD','min_qualifications_engineering','min_qualifications_experience']
X_test[cols] = X_test[cols].applymap(np.int64)
X_test

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:3391: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[k1] = value[k2]

,DA,accounting,advertising,coding,communication,designing,languages,leadership,management,marketing,math,webDev,min_qualifications_BA/BS,min_qualifications_BBA,min_qualifications_BS,min_qualifications_PhD,min_qualifications_engineering,min_qualifications_experience
0,0,0,1,0,0,0,0,1,0,1,0,1,1,0,0,0,0,0
1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0
2,0,1,0,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0
3,0,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0
4,0,0,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0
5,0,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,1,0
6,0,0,0,1,0,1,0,0,1,1,1,0,0,0,1,0,0,0
7,0,1,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0
8,1,0,0,1,1,0,0,1,0,0,1,0,0,0,0,0,1,0
9,0,0,0,0,0,0,1,1,1,0,1,0,1,0,0,0,0,0
10,0,1,0,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0
11,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0
12,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0
13,0,0,0,0,1,0,0,0,1,1,0,0,0,1,0,0,0,0
14,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,1,0
15,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0
16,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0
17,0,1,0,0,1,0,0,0,1,0,1,0,1,0,0,0,0,0
18,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0
19,0,0,1,0,0,0,0,1,1,1,0,0,0,0,1,0,0,0
20,0,0,0,1,0,0,0,1,1,1,0,1,0,0,0,1,0,0
21,0,0,0,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0
22,0,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,0
23,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0
24,1,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,0,1
25,1,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0
26,0,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0
27,1,0,0,1,1,0,0,1,1,0,0,0,0,0,0,0,0,1
28,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0
29,0,1,0,0,1,0,1,0,0,0,0,0,1,0,0,0,0,0
30,0,1,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0
31,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,1,0
32,0,1,0,1,1,1,0,0,0,0,1,0,0,0,0,0,1,0
33,0,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0
34,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1
35,0,0,1,0,0,0,0,1,1,1,0,0,0,0,0,0,1,0
36,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0,0,1,0
37,0,0,0,0,1,0,1,0,1,0,0,0,0,1,0,0,0,0
38,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0
39,1,0,1,1,0,0,0,1,0,0,0,1,0,0,0,0,1,0
40,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0
41,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0
42,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,1
43,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0
44,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,1,0
45,0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,1,0
46,1,0,0,1,0,0,0,1,1,0,0,1,0,0,0,0,1,0
47,0,0,0,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0
48,1,0,0,1,1,0,0,1,0,0,0,1,1,0,0,0,0,0

In [24]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 8,algorithm='auto')
classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=8, p=2,
           weights='uniform')

In [25]:
y_pred = classifier.predict(X_test)

In [26]:
y_pred

array(['Big Data Product Specialist, Google Cloud (English)',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Associate Account Strategist (Ukrainian), GMS Sales',
       'Chief of Staff, Google Hardware',
       'Chief of Staff, Google Hardware',
       'High Performance Computing (HPC) Specialist, Google Cloud',
       'Associate Account Strategist (Ukrainian), GMS Sales',
       'Chief of Staff, Google Hardware',
       'Data Analyst, Product and Tools Operations, Google Technical Services',
       'Head of Partner Engineering, Google Cloud',
       'Solution Architect, Google Cloud Platform (Apigee)',
       'Data Analyst, Product and Tools Operations, Google Technical Services',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Associate Account Strategist (Ukrainian), GMS Sales',
       'Associate Account Strategist (Ukrainian), GMS Sales',
       'Big Data Product Specialist, Google Cloud (English)',
       'Data Analyst, Product and Tools Operations, Google Technical Services',
       'Chief of Staff, Google Hardware',
       'Solutions Architect, Healthcare and Life Sciences, Google Cloud',
       'Big Data Product Specialist, Google Cloud (English)',
       'Big Data Product Specialist, Google Cloud (English)',
       'Google Cloud Program Manager', 'Google Cloud Program Manager',
       'Global Supply Chain Manager, Display/Touch, Consumer Hardware',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Data Analyst, Product and Tools Operations, Google Technical Services',
       'Solution Architect, Google Cloud Platform (Apigee)',
       'Data Analyst, Consumer Hardware', 'Google Cloud Program Manager',
       'Solutions Architect, Healthcare and Life Sciences, Google Cloud',
       'Solutions Architect, Healthcare and Life Sciences, Google Cloud',
       'Big Data Product Specialist, Google Cloud (English)',
       'Solution Architect, Google Cloud Platform (Apigee)',
       'Google Cloud Program Manager',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Big Data Product Specialist, Google Cloud (English)',
       'Graphics Software Engineer, Robotics Simulation, Google Cloud Platform',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Solution Architect, Google Cloud Platform (Apigee)',
       'Big Data Product Specialist, Google Cloud (English)',
       'Big Data Product Specialist, Google Cloud (English)',
       'Global Supply Chain Manager, Display/Touch, Consumer Hardware',
       'Measurement Solutions Consultant, Google Technical Services',
       'Associate Account Strategist (Czech/Slovak), Global Customer Experience',
       'Head of Partner Engineering, Google Cloud',
       'Graphics Software Engineer, Robotics Simulation, Google Cloud Platform',
       'Big Data Product Specialist, Google Cloud (English)',
       'Google Cloud Program Manager', 'Data Analyst, Consumer Hardware'],
      dtype=object)

In [27]:
res=pd.DataFrame(y_pred, columns=['result'])
res

                                               result
0   Big Data Product Specialist, Google Cloud (Eng...
1   Associate Account Strategist (Czech/Slovak), G...
2   Associate Account Strategist (Ukrainian), GMS ...
3                     Chief of Staff, Google Hardware
4                     Chief of Staff, Google Hardware
5   High Performance Computing (HPC) Specialist, G...
6   Associate Account Strategist (Ukrainian), GMS ...
7                     Chief of Staff, Google Hardware
8   Data Analyst, Product and Tools Operations, Go...
9           Head of Partner Engineering, Google Cloud
10  Solution Architect, Google Cloud Platform (Api...
11  Data Analyst, Product and Tools Operations, Go...
12  Associate Account Strategist (Czech/Slovak), G...
13  Associate Account Strategist (Ukrainian), GMS ...
14  Associate Account Strategist (Ukrainian), GMS ...
15  Big Data Product Specialist, Google Cloud (Eng...
16  Data Analyst, Product and Tools Operations, Go...
17                    Chief of Staff, Google Hardware
18  Solutions Architect, Healthcare and Life Scien...
19  Big Data Product Specialist, Google Cloud (Eng...
20  Big Data Product Specialist, Google Cloud (Eng...
21                       Google Cloud Program Manager
22                       Google Cloud Program Manager
23  Global Supply Chain Manager, Display/Touch, Co...
24  Associate Account Strategist (Czech/Slovak), G...
25  Data Analyst, Product and Tools Operations, Go...
26  Solution Architect, Google Cloud Platform (Api...
27                    Data Analyst, Consumer Hardware
28                       Google Cloud Program Manager
29  Solutions Architect, Healthcare and Life Scien...
30  Solutions Architect, Healthcare and Life Scien...
31  Big Data Product Specialist, Google Cloud (Eng...
32  Solution Architect, Google Cloud Platform (Api...
33                       Google Cloud Program Manager
34  Associate Account Strategist (Czech/Slovak), G...
35  Big Data Product Specialist, Google Cloud (Eng...
36  Graphics Software Engineer, Robotics Simulatio...
37  Associate Account Strategist (Czech/Slovak), G...
38  Solution Architect, Google Cloud Platform (Api...
39  Big Data Product Specialist, Google Cloud (Eng...
40  Big Data Product Specialist, Google Cloud (Eng...
41  Global Supply Chain Manager, Display/Touch, Co...
42  Measurement Solutions Consultant, Google Techn...
43  Associate Account Strategist (Czech/Slovak), G...
44          Head of Partner Engineering, Google Cloud
45  Graphics Software Engineer, Robotics Simulatio...
46  Big Data Product Specialist, Google Cloud (Eng...
47                       Google Cloud Program Manager
48                    Data Analyst, Consumer Hardware

In [28]:
name=student.loc[:,"SName"]

In [29]:
name

0          Mary
1          Anna
2      Margaret
3     Elizabeth
4          Emma
5      Florence
6         Ethel
7        Minnie
8         Helen
9        Bertha
10        Clara
11       Bessie
12        Annie
13        Grace
14        Mabel
15        Alice
16          Ida
17         Edna
18         Ruth
19      Lillian
20       Martha
21         Rose
22         Ella
23        Sarah
24       Nellie
25     Gertrude
26        Pearl
27        Marie
28        Edith
29        Laura
30       Myrtle
31        Hazel
32          Eva
33      Frances
34         Cora
35       Carrie
36       Louise
37        Elsie
38       Lillie
39       Jennie
40    Catherine
41       Hattie
42        Julia
43        Maude
44         Lena
45       Mattie
46       Agnesh
47       Jessie
48    Josephine
49         Lula
50          Ada
51        Irene
52        Lucky
53      Balloon
Name: SName, dtype: object

In [30]:
result=pd.concat([name,res],axis=1)

result

In [31]:
result

        SName                                             result
0        Mary  Big Data Product Specialist, Google Cloud (Eng...
1        Anna  Associate Account Strategist (Czech/Slovak), G...
2    Margaret  Associate Account Strategist (Ukrainian), GMS ...
3   Elizabeth                    Chief of Staff, Google Hardware
4        Emma                    Chief of Staff, Google Hardware
5    Florence  High Performance Computing (HPC) Specialist, G...
6       Ethel  Associate Account Strategist (Ukrainian), GMS ...
7      Minnie                    Chief of Staff, Google Hardware
8       Helen  Data Analyst, Product and Tools Operations, Go...
9      Bertha          Head of Partner Engineering, Google Cloud
10      Clara  Solution Architect, Google Cloud Platform (Api...
11     Bessie  Data Analyst, Product and Tools Operations, Go...
12      Annie  Associate Account Strategist (Czech/Slovak), G...
13      Grace  Associate Account Strategist (Ukrainian), GMS ...
14      Mabel  Associate Account Strategist (Ukrainian), GMS ...
15      Alice  Big Data Product Specialist, Google Cloud (Eng...
16        Ida  Data Analyst, Product and Tools Operations, Go...
17       Edna                    Chief of Staff, Google Hardware
18       Ruth  Solutions Architect, Healthcare and Life Scien...
19    Lillian  Big Data Product Specialist, Google Cloud (Eng...
20     Martha  Big Data Product Specialist, Google Cloud (Eng...
21       Rose                       Google Cloud Program Manager
22       Ella                       Google Cloud Program Manager
23      Sarah  Global Supply Chain Manager, Display/Touch, Co...
24     Nellie  Associate Account Strategist (Czech/Slovak), G...
25   Gertrude  Data Analyst, Product and Tools Operations, Go...
26      Pearl  Solution Architect, Google Cloud Platform (Api...
27      Marie                    Data Analyst, Consumer Hardware
28      Edith                       Google Cloud Program Manager
29      Laura  Solutions Architect, Healthcare and Life Scien...
30     Myrtle  Solutions Architect, Healthcare and Life Scien...
31      Hazel  Big Data Product Specialist, Google Cloud (Eng...
32        Eva  Solution Architect, Google Cloud Platform (Api...
33    Frances                       Google Cloud Program Manager
34       Cora  Associate Account Strategist (Czech/Slovak), G...
35     Carrie  Big Data Product Specialist, Google Cloud (Eng...
36     Louise  Graphics Software Engineer, Robotics Simulatio...
37      Elsie  Associate Account Strategist (Czech/Slovak), G...
38     Lillie  Solution Architect, Google Cloud Platform (Api...
39     Jennie  Big Data Product Specialist, Google Cloud (Eng...
40  Catherine  Big Data Product Specialist, Google Cloud (Eng...
41     Hattie  Global Supply Chain Manager, Display/Touch, Co...
42      Julia  Measurement Solutions Consultant, Google Techn...
43      Maude  Associate Account Strategist (Czech/Slovak), G...
44       Lena          Head of Partner Engineering, Google Cloud
45     Mattie  Graphics Software Engineer, Robotics Simulatio...
46     Agnesh  Big Data Product Specialist, Google Cloud (Eng...
47     Jessie                       Google Cloud Program Manager
48  Josephine                    Data Analyst, Consumer Hardware
49       Lula                                                NaN
50        Ada                                                NaN
51      Irene                                                NaN
52      Lucky                                                NaN
53    Balloon                                                NaN

In [32]:
result.dropna()

        SName                                             result
0        Mary  Big Data Product Specialist, Google Cloud (Eng...
1        Anna  Associate Account Strategist (Czech/Slovak), G...
2    Margaret  Associate Account Strategist (Ukrainian), GMS ...
3   Elizabeth                    Chief of Staff, Google Hardware
4        Emma                    Chief of Staff, Google Hardware
5    Florence  High Performance Computing (HPC) Specialist, G...
6       Ethel  Associate Account Strategist (Ukrainian), GMS ...
7      Minnie                    Chief of Staff, Google Hardware
8       Helen  Data Analyst, Product and Tools Operations, Go...
9      Bertha          Head of Partner Engineering, Google Cloud
10      Clara  Solution Architect, Google Cloud Platform (Api...
11     Bessie  Data Analyst, Product and Tools Operations, Go...
12      Annie  Associate Account Strategist (Czech/Slovak), G...
13      Grace  Associate Account Strategist (Ukrainian), GMS ...
14      Mabel  Associate Account Strategist (Ukrainian), GMS ...
15      Alice  Big Data Product Specialist, Google Cloud (Eng...
16        Ida  Data Analyst, Product and Tools Operations, Go...
17       Edna                    Chief of Staff, Google Hardware
18       Ruth  Solutions Architect, Healthcare and Life Scien...
19    Lillian  Big Data Product Specialist, Google Cloud (Eng...
20     Martha  Big Data Product Specialist, Google Cloud (Eng...
21       Rose                       Google Cloud Program Manager
22       Ella                       Google Cloud Program Manager
23      Sarah  Global Supply Chain Manager, Display/Touch, Co...
24     Nellie  Associate Account Strategist (Czech/Slovak), G...
25   Gertrude  Data Analyst, Product and Tools Operations, Go...
26      Pearl  Solution Architect, Google Cloud Platform (Api...
27      Marie                    Data Analyst, Consumer Hardware
28      Edith                       Google Cloud Program Manager
29      Laura  Solutions Architect, Healthcare and Life Scien...
30     Myrtle  Solutions Architect, Healthcare and Life Scien...
31      Hazel  Big Data Product Specialist, Google Cloud (Eng...
32        Eva  Solution Architect, Google Cloud Platform (Api...
33    Frances                       Google Cloud Program Manager
34       Cora  Associate Account Strategist (Czech/Slovak), G...
35     Carrie  Big Data Product Specialist, Google Cloud (Eng...
36     Louise  Graphics Software Engineer, Robotics Simulatio...
37      Elsie  Associate Account Strategist (Czech/Slovak), G...
38     Lillie  Solution Architect, Google Cloud Platform (Api...
39     Jennie  Big Data Product Specialist, Google Cloud (Eng...
40  Catherine  Big Data Product Specialist, Google Cloud (Eng...
41     Hattie  Global Supply Chain Manager, Display/Touch, Co...
42      Julia  Measurement Solutions Consultant, Google Techn...
43      Maude  Associate Account Strategist (Czech/Slovak), G...
44       Lena          Head of Partner Engineering, Google Cloud
45     Mattie  Graphics Software Engineer, Robotics Simulatio...
46     Agnesh  Big Data Product Specialist, Google Cloud (Eng...
47     Jessie                       Google Cloud Program Manager
48  Josephine                    Data Analyst, Consumer Hardware

In [33]:
result.to_csv("C:\\Users\\RASHMI\\Desktop\\SIH\\output.csv")

In [ ]:
def recommend(desired_name):
    res1=pd.read_csv("C:\\Users\\RASHMI\\Desktop\\SIH\\output.csv")
    records=result.loc[ds['SName'] == desired_name]
    print desired_name

In [ ]:
df1_skills